# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 15:17
from __future__ import unicode_literals

import content.slug
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('events', '0001_initial'), ('events', '0002_auto_20160604_1823'), ('events', '0003_auto_20160604_1914'), ('events', '0004_auto_20160821_1833'), ('events', '0005_auto_20160911_1541'), ('events', '0006_auto_20161002_2303'), ('events', '0007_externalevent'), ('events', '0008_auto_20180811_1446'), ('events', '0009_auto_20180811_1514'), ('events', '0010_delete_fbevent'), ('events', '0011_externalevent_starts_on'), ('events', '0012_remove_externalevent_starts_at'), ('events', '0013_auto_20180812_0952')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(help_text='Imię i nazwisko wykonawcy lub nazwa zespołu.', max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(content.slug.SlugLogicMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa wydarzenia, w tym występujący artysta lub zespół.', max_length=100, verbose_name='Nazwa')),
                ('url', models.URLField(help_text='Strona internetowa wydarzenia (może być na Facebooku).', verbose_name='Strona internetowa')),
                ('town', models.CharField(help_text='Miejscowość w którym odbywa się wydarzenie.', max_length=100, verbose_name='Miejscowość')),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('starts_on', models.DateField(default=datetime.date(2018, 8, 11), help_text='Data rozpoczęcia wydarzenia.', verbose_name='Dzień rozpoczęcia')),
            ],
        ),
    ]
