# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_squashed_0013_auto_20180812_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalevent',
            name='starts_on',
            field=models.DateField(help_text='Data rozpoczęcia wydarzenia.', verbose_name='Dzień rozpoczęcia'),
        ),
    ]
