# Generated by Django 3.0.7 on 2020-08-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180812_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalevent',
            name='town',
            field=models.CharField(blank=True, help_text='Miejscowość w którym odbywa się wydarzenie (zostaw puste jeśli to wydarzenie online).', max_length=100, null=True, verbose_name='Miejscowość'),
        ),
    ]
