# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160911_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': [], 'ordering': ['datetime']},
        ),
    ]
