# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20161002_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa wydarzenia, w tym występujący artysta lub zespół.', max_length=100)),
                ('starts_at', models.DateTimeField(editable=False, help_text='Data i godzina rozpoczęcia wydarzenia.')),
                ('url', models.URLField(help_text='Strona internetowa wydarzenia (może być na Facebooku).')),
                ('town', models.CharField(help_text='Miejscowość w którym odbywa się wydarzenie.', max_length=100)),
                ('lat', models.FloatField(blank=True, editable=False, null=True)),
                ('lon', models.FloatField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
