# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-11 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_externalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalevent',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina rozpoczęcia wydarzenia.'),
        ),
    ]
