# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20180811_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalevent',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='name',
            field=models.CharField(help_text='Nazwa wydarzenia, w tym występujący artysta lub zespół.', max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='starts_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina rozpoczęcia wydarzenia.', verbose_name='Czas rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='town',
            field=models.CharField(help_text='Miejscowość w którym odbywa się wydarzenie.', max_length=100, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='externalevent',
            name='url',
            field=models.URLField(help_text='Strona internetowa wydarzenia (może być na Facebooku).', verbose_name='Strona internetowa'),
        ),
    ]
