# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-11 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_externalevent_starts_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalevent',
            name='starts_at',
        ),
    ]
