# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-06 11:24
from __future__ import unicode_literals

import content.slug
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('articles', '0001_initial'), ('articles', '0002_auto_20161002_2303'), ('articles', '0003_auto_20171129_2100')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0010_remove_song_link_wrzuta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed', models.BooleanField(default=False, editable=False)),
                ('pub_date', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('title', models.CharField(help_text='Tytuł artykułu, np. \'IX Festiwal Piosenki Poetyckiej im. Jacka Kaczmarskiego "Nadzieja"\'.', max_length=100)),
                ('lead_text_trevor', models.TextField()),
                ('main_text_trevor', models.TextField()),
                ('cover_image', models.ImageField(blank=True, help_text='Main illustration for the article.', null=True, upload_to='article_covers')),
                ('cover_credits_trevor', models.TextField(blank=True, null=True)),
                ('lead_text_html', models.TextField(editable=False)),
                ('main_text_html', models.TextField(editable=False)),
                ('cover_credits_html', models.TextField(blank=True, editable=False, null=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
                'abstract': False,
                'default_permissions': [],
            },
            bases=(content.slug.SlugLogicMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SongMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='songmention',
            unique_together=set([('article', 'song')]),
        ),
    ]
