# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'default_permissions': [], 'ordering': ['-pub_date']},
        ),
    ]
