# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-29 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_remove_song_link_wrzuta'),
        ('articles', '0002_auto_20161002_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Song')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='songmention',
            unique_together=set([('article', 'song')]),
        ),
    ]
