runtime: python311

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static
  secure: always

- url: /
  static_files: out/index.html
  upload: out/index.html
  secure: always

- url: /artykuly/
  static_files: out/artykuly/index.html
  upload: out/artykuly/index.html
  secure: always

- url: /artykuly/(.*)/
  static_files: out/artykuly/\1/index.html
  upload: out/artykuly/.*/index.html

- url: /blog/
  static_files: out/blog/index.html
  upload: out/blog/index.html
  secure: always

- url: /blog/(.*)/
  static_files: out/blog/\1/index.html
  upload: out/blog/.*/index.html

- url: /spiewnik/
  static_files: out/spiewnik/index.html
  upload: out/spiewnik/index.html
  secure: always

- url: /spiewnik/(.*)/
  static_files: out/spiewnik/\1/index.html
  upload: out/spiewnik/.*/index.html

- url: /opracowanie/(.*)/
  static_files: out/opracowanie/\1/index.html
  upload: out/opracowanie/.*/index.html

- url: /o-stronie/
  static_files: out/o-stronie/index.html
  upload: out/o-stronie/index.html
  secure: always

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  secure: always

- url: /index/artists.json
  static_files: out/index/artists.json
  upload: out/index/artists.json

- url: /index/songs.json
  static_files: out/index/songs.json
  upload: out/index/songs.json

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always

includes:
  - private_gae_env.yaml

instance_class: F1
automatic_scaling:
  max_idle_instances: 1
  max_instances: 3