# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarouselItem',
        ),
    ]
