# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-06-06 11:27
from __future__ import unicode_literals

import content.slug
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('blog', '0001_initial'), ('blog', '0002_auto_20161002_2303')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed', models.BooleanField(default=False, editable=False)),
                ('pub_date', models.DateTimeField(editable=False)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('title', models.CharField(help_text="Tytuł posta, np. 'Nowa wyszukiwarka piosenek.'.", max_length=100)),
                ('post_trevor', models.TextField()),
                ('more_trevor', models.TextField(blank=True, null=True)),
                ('post_html', models.TextField(editable=False, null=True)),
                ('more_html', models.TextField(editable=False, null=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pub_date'],
                'default_permissions': [],
                'abstract': False,
            },
            bases=(content.slug.SlugLogicMixin, models.Model),
        ),
    ]
