# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_squashed_0018_auto_20180812_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='songnote',
            name='date',
            field=models.DateField(blank=True, help_text='Data wydarzenia, do którego odnosi się notka', null=True),
        ),
        migrations.AddField(
            model_name='songnote',
            name='date_description',
            field=models.CharField(blank=True, help_text='Opis wydarzenia, do którego odnosi się notka', max_length=100, null=True),
        ),
    ]
