# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-02 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_artistnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='artistnote',
            options={'default_permissions': []},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'default_permissions': [], 'ordering': ['title', 'disambig']},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='description_trevor',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_author',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_url',
        ),
    ]
