# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20161002_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='author',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='reviewed',
        ),
    ]
