# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 19:24
from __future__ import unicode_literals

import content.slug
import content.url_scheme
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0008_auto_20161027_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('reviewed', models.BooleanField(default=False, editable=False)),
                ('pub_date', models.DateTimeField(editable=False)),
                ('title', models.CharField(help_text='Tytuł adnotacji.', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Ilustracja.', null=True, upload_to='notes')),
                ('image_url', models.URLField(blank=True, help_text='Źródło zdjęcia (adres www).', null=True)),
                ('image_author', models.CharField(blank=True, help_text='Źródło zdjęcia (autor).', max_length=50, null=True)),
                ('text_trevor', models.TextField(help_text='Treść adnotacji.')),
                ('text_html', models.TextField(editable=False)),
                ('url1', models.URLField(blank=True, help_text='Źródło (adres www).', null=True)),
                ('url2', models.URLField(blank=True, help_text='Źródło (adres www).', null=True)),
                ('ref1', models.TextField(blank=True, help_text='Źródło (nazwa i autor publikacji).', null=True)),
                ('ref2', models.TextField(blank=True, help_text='Źródło (nazwa i autor publikacji).', null=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': [],
            },
            bases=(content.url_scheme.EditReviewApprove, content.slug.SlugLogicMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='song',
            name='disambig',
            field=models.CharField(blank=True, help_text='Adnotacja rozróżniająca piosenki o tym samym tytule.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='original_title',
            field=models.CharField(blank=True, help_text='Tytuł oryginalnej piosenki w przypadku tłumaczenia.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='songnote',
            name='song',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='songs.Song'),
        ),
    ]
