# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-08 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20161027_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='link_wrzuta',
        ),
    ]
