# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-19 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_remove_song_link_wrzuta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='song',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
    ]
