# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-28 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_song_artist_for_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_for_slug',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
