# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-28 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_auto_20180728_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistnote',
            name='artist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Artist'),
        ),
        migrations.AlterField(
            model_name='songnote',
            name='song',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Song'),
        ),
    ]
