# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0015_remove_song_old_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistnote',
            name='image_license',
            field=models.CharField(blank=True, help_text='Źródło zdjęcia (licencja).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='songnote',
            name='image_license',
            field=models.CharField(blank=True, help_text='Źródło zdjęcia (licencja).', max_length=50, null=True),
        ),
    ]
