# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-08-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0017_artist_cover_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='cover_note',
            field=models.ForeignKey(blank=True, help_text='Notka której ilustracja może służyć za okładkę.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_covered', to='songs.ArtistNote'),
        ),
    ]
