name: Publish to Firebase

on:
  push:
    branches:
      - main

jobs:
  generate-and-publish:
    name: Generate output files and publish to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment and build site
        uses: ./.github/actions/setup-and-build
        with:
          calendar_api_key: ${{ secrets.CALENDAR_API_KEY }}

      - name: Publish to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --project piosenka-site --token "$FIREBASE_TOKEN"
